version: '3.8'

services:
  api:
    build: .
    container_name: pinterest-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000

  streamlit:
    build: .
    container_name: pinterest-ui
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    command: streamlit run app/streamlit_ui.py
    depends_on:
      - api
